// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzJ-4GvG2KQrRkXkkLTdKxDxDnhojLiGc',
    appId: '1:783079390441:web:4280c4a7ccdd7417aac478',
    messagingSenderId: '783079390441',
    projectId: 'cpd-home-car-finder',
    authDomain: 'cpd-home-car-finder.firebaseapp.com',
    storageBucket: 'cpd-home-car-finder.firebasestorage.app',
    measurementId: 'G-75H32XHJ6Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv3xVywBw67uPHjSGNYx5NvZH5DcOiK_o',
    appId: '1:783079390441:android:3b36899767b4bdbcaac478',
    messagingSenderId: '783079390441',
    projectId: 'cpd-home-car-finder',
    storageBucket: 'cpd-home-car-finder.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzJ-4GvG2KQrRkXkkLTdKxDxDnhojLiGc',
    appId: '1:783079390441:web:a870e1814f4295dcaac478',
    messagingSenderId: '783079390441',
    projectId: 'cpd-home-car-finder',
    authDomain: 'cpd-home-car-finder.firebaseapp.com',
    storageBucket: 'cpd-home-car-finder.firebasestorage.app',
    measurementId: 'G-QWQ94M0VNJ',
  );
}
